# !/usr/bin/python
"""
Defines the various robot GPIO pins
"""

# Motor Pins Original
MOTOR_LEFT_FORWARD_PIN = 36  # GPIO16
MOTOR_LEFT_BACKWARD_PIN = 35  # GPIO19
MOTOR_RIGHT_FORWARD_PIN = 33  # GPIO13
MOTOR_RIGHT_BACKWARD_PIN = 32  # GPIO12

# Motor Pins two controllers
MOTOR_LEFT_FRONT_FORWARD_PIN = 29  # GPIO5
MOTOR_LEFT_FRONT_BACKWARD_PIN = 37  # GPIO26
MOTOR_LEFT_REAR_FORWARD_PIN = 35  # GPIO19
MOTOR_LEFT_REAR_BACKWARD_PIN = 32  # GPIO12
MOTOR_RIGHT_FRONT_FORWARD_PIN = 7  # GPIO4
MOTOR_RIGHT_FRONT_BACKWARD_PIN = 11  # GPIO17
MOTOR_RIGHT_REAR_FORWARD_PIN = 33  # GPIO13
MOTOR_RIGHT_REAR_BACKWARD_PIN = 36  # GPIO16

# Duck Shoot
DUCK_SHOOT_FIRE = 13  # GPIO 27
DUCK_SHOOT_LASER = 99
DUCK_SHOOT_MOTOR = 99

# Not currently in design
MOTOR_DRIVE_FORWARD_PIN = 99
MOTOR_DRIVE_BACKWARD_PIN = 99
MOTOR_ELEVATION_PIN = 99
MOTOR_DECLINATION_PIN = 99

# Define Sonar Pins
SONAR_FRONT_TX_PIN = 38  # GPIO20
SONAR_FRONT_RX_PIN = 38  # GPIO20

SONAR_LEFT_TX_PIN = 12  # GPIO18
SONAR_LEFT_RX_PIN = 15  # GPIO22

SONAR_RIGHT_TX_PIN = 31  # GPIO6
SONAR_RIGHT_RX_PIN = 16  # GPIO23

# Line follower
# Pins used for dual motor controllers
LINE_FOLLOWER_LEFT_PIN = 7  # GPIO4
LINE_FOLLOWER_MIDDLE_PIN = 11  # GPIO17
LINE_FOLLOWER_RIGHT_PIN = 29  # GPIO5

# Servo Pins
SERVO_HORIZONTAL_PIN = 22  # GPIO25
SERVO_VERTICAL_PIN = 18  # GPIO24
