# !/usr/bin/python

"""
Defines the pins in use for the initio robot
"""

# Motor Pins Original
MOTOR_LEFT_FORWARD_PIN = 36
MOTOR_LEFT_BACKWARD_PIN = 35
MOTOR_RIGHT_FORWARD_PIN = 33
MOTOR_RIGHT_BACKWARD_PIN = 32

# Motor Pins two controllers
MOTOR_LEFT_FRONT_FORWARD_PIN = 35
MOTOR_LEFT_FRONT_BACKWARD_PIN = 36
MOTOR_LEFT_REAR_FORWARD_PIN = 7
MOTOR_LEFT_REAR_BACKWARD_PIN = 11
MOTOR_RIGHT_FRONT_FORWARD_PIN = 33
MOTOR_RIGHT_FRONT_BACKWARD_PIN = 32
MOTOR_RIGHT_REAR_FORWARD_PIN = 29
MOTOR_RIGHT_REAR_BACKWARD_PIN = 37

# Duck Shoot 
MOTOR_DRIVE_FORWARD_PIN = 99
MOTOR_DRIVE_BACKWARD_PIN = 99
MOTOR_ELEVATION_PIN = 99
MOTOR_DECLINATION_PIN = 99

DUCK_SHOOT_LASER = 99
DUCK_SHOOT_FIRE = 99

# Define Sonar Pins
SONAR_FRONT_TX_PIN = 38
SONAR_FRONT_RX_PIN = 38

SONAR_LEFT_TX_PIN = 12
SONAR_LEFT_RX_PIN = 15

SONAR_RIGHT_TX_PIN = 31
SONAR_RIGHT_RX_PIN = 16

# Line follower
LINE_FOLLOWER_LEFT_PIN = 7
LINE_FOLLOWER_MIDDLE_PIN = 11
LINE_FOLLOWER_RIGHT_PIN = 29
