# !/usr/bin/python
"""
Defines the various 2018 robot GPIO pins
"""

# Motor Pins two controllers
MOTOR_LEFT_FRONT_FORWARD_GPIO = 5  # Pin 29
MOTOR_LEFT_FRONT_BACKWARD_GPIO = 26  # Pin 37
MOTOR_LEFT_REAR_FORWARD_GPIO = 19  # Pin 35
MOTOR_LEFT_REAR_BACKWARD_GPIO = 12  # Pin 32
MOTOR_RIGHT_FRONT_FORWARD_GPIO = 4  # Pin 7
MOTOR_RIGHT_FRONT_BACKWARD_GPIO = 17  # Pin 11
MOTOR_RIGHT_REAR_FORWARD_GPIO = 13  # Pin 33
MOTOR_RIGHT_REAR_BACKWARD_GPIO = 16  # Pin 36

# Duck Shoot
DUCK_SHOOT_FIRE_PIN = 13  # GPIO27
DUCK_SHOOT_LASER_GPIO = 14  # Pin 8
DUCK_SHOOT_MOTOR_GPIO = 21  # Pin 40

# Define Sonar Pins
SONAR_FRONT_TX_GPIO = 20  # Pin 38
SONAR_FRONT_RX_GPIO = 20  # Pin 38
SONAR_LEFT_TX_GPIO = 18  # Pin 12
SONAR_LEFT_RX_GPIO = 22  # Pin 15
SONAR_RIGHT_TX_GPIO = 6  # Pin 31
SONAR_RIGHT_RX_GPIO = 23  # Pin 16

# Line follower
# Pins used for dual motor controllers
LINE_FOLLOWER_LEFT_GPIO = 4  # Pin 7
LINE_FOLLOWER_MIDDLE_GPIO = 17  # Pin 11
LINE_FOLLOWER_RIGHT_GPIO = 5  # Pin 29

# Servo Pins
SERVO_HORIZONTAL_PIN = 22  # GPIO25
SERVO_VERTICAL_PIN = 18  # GPIO24
