# !/usr/bin/python
"""
Defines some basic speed settings
"""

SPEED_FASTEST = 100
SPEED_FAST = 80
SPEED_MEDIUM = 50
SPEED_SLOW = 40
SPEED_VERYSLOW = 30
SPEED_VERYVERYSLOW = 20

# SPEED_FASTEST = 100
# SPEED_FAST = 80
# SPEED_MEDIUM = 50
# SPEED_SLOW = 40
# SPEED_VERYSLOW = 30
# SPEED_VERYVERYSLOW = 20
